### ISSUE TITLE
If a failure message contains a ':' , it is cut off by the parser

### ISSUE THREAD

**Issue by FabioCZ** [dpreussler/automator-log-converter#3]
E.g. Message in uiatutomator output is : 
`assertTrue failed, The desired time string is not properly formatted, given, 1:09:50:10`

This gets parsed down to the xml file:
`assertTrue failed, The desired time string is not properly formatted, given, 1`

Possible solution is to add a limit to split method call in Converter.java:85 , so it would be like: `String[] errorSeperated = error.split(":", 2);`

**Comment by dpreussler** [comment]
thanks for letting me know. Try the updated version
